title: Schüttelgericht
description: Discover AI-powered recipe inspiration with a shake of your phone! Turn your available ingredients into delicious meals instantly.
baseurl: ""
url: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Collections
collections:
  recipes:
    output: true
    permalink: /recipes/:path/

defaults:
  - scope:
      path: ""
      type: "recipes"
    values:
      layout: "recipe"
      
# SEO settings
lang: de_DE
social:
  name: Schüttelgericht
  links:
    - https://github.com/TrimeraDev/Schuettelgericht

# Analytics (you'll need to add your tracking ID)
# google_analytics: UA-XXXXXXXX-X
